# Generated by Django 4.0.1 on 2022-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_rename_channels_channel_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='desc',
            field=models.TextField(),
        ),
    ]
