# Generated by Django 4.0.1 on 2022-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_alter_forum_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
